const script = `
CREATE TABLE sk_official_admin (
admin_id SERIAL NOT NULL PRIMARY KEY,
first_name VARCHAR(55) NOT NULL,
last_name VARCHAR(55) NOT NULL,
email VARCHAR(55) UNIQUE NOT NULL,
organization VARCHAR(55) NOT NULL,
password TEXT UNIQUE NOT NULL,
role VARCHAR(50) NOT NULL CHECK(role IN ('super_sk_admin', 'natural_sk_admin)),
createdAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
`